### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by CaroRob** [MassLegalHelp/docassemble-LRFGuideMe#13]
From Jonathan in Slack 2021-02-27, 6:05 PM :
If you are using the spreadsheet translation feature for translation, I don't know why you would have `en.yml` and `es.yml`; you would only need one version of the YAML written in English.
Spreadsheet translation files do not affect the names of document templates that you specify with `docx template file` or `content file`.
If you want different template files to be used depending on the language, you could do something like:
```
attachment:
  variable name: motion_dismiss
  name: Motion To Dismiss
  docx template file:
    code: |
      'motion_to_dismiss_' + get_language() + '.docx'
```
This assumes the files are named `motion_to_dismiss_es.docx` and `motion_to_dismiss_en.docx`.
Alternatively, you could do something like this:
```
attachment:
  variable name: motion_dismiss
  name: Motion To Dismiss
  docx template file: motion_to_dismiss.docx
---
if: get_langugage() == 'es'
attachment:
  variable name: motion_dismiss
  name: Motion To Dismiss
  docx template file: Spanish_motion_to_dismiss.docx
---
if: get_langugage() == 'de'
attachment:
  variable name: motion_dismiss
  name: Motion To Dismiss
  docx template file: German_motion_to_dismiss.docx
```

**Comment by CaroRob** [comment]
Getting Unicode error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 4: invalid continuation byte

**Comment by purplesky2016** [comment]
Close it as the Master branch doesn't have this issue. It was created for a development branch.
